version: '3.9'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9092
      KAFKA_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_NAME: INSIDE
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  ragamuffin-index:
    build: 
      context: .
      dockerfile: ./ragamuffin_index/Dockerfile
    volumes:
      - ./ragamuffin_index:/usr/src/app/ragamuffin_index
      - ./ragamuffin_core:/usr/src/app/ragamuffin_core
    ports:
      - 8002:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - LLAMA_CLOUD_API_KEY=${LLAMA_CLOUD_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - EMBED_MODEL_ID=${EMBED_MODEL_ID}
      - NEO4J_URI=${NEO4J_URI}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_FILES_PATH=${AWS_FILES_PATH}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - RDS_DB_INSTANCE=${RDS_DB_INSTANCE}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DB_USER=${RDS_DB_USER}
      - RDS_DB_PASSWORD=${RDS_DB_PASSWORD}
      - RDS_DB_PORT=${RDS_DB_PORT}
    depends_on:
     - kafka

  ragamuffin-files:
    build: 
      context: .
      dockerfile: ./ragamuffin_files/Dockerfile
    volumes:
      - ./ragamuffin_files:/usr/src/app/ragamuffin_files
      - ./ragamuffin_core:/usr/src/app/ragamuffin_core
    ports:
      - 8001:8000
    environment:
      - PYTHONPATH=/usr/src
      - PYTHONUNBUFFERED=TRUE
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_FILES_PATH=${AWS_FILES_PATH}
      - KAFKA_TOPIC=${KAFKA_TOPIC}
      - KAFKA_BOOTSTRAP=${KAFKA_BOOTSTRAP}
      - LOCAL_FILES_PATH=${LOCAL_FILES_PATH}
      - RDS_DB_INSTANCE=${RDS_DB_INSTANCE}
      - RDS_DB_NAME=${RDS_DB_NAME}
      - RDS_DB_USER=${RDS_DB_USER}
      - RDS_DB_PASSWORD=${RDS_DB_PASSWORD}
      - RDS_DB_PORT=${RDS_DB_PORT}
    depends_on:
     - kafka